tsl:
  loadAlwaysFromCache: false
  url: https://ec.europa.eu/information_society/policy/esignature/trusted-list/tl-mp.xml
  code: EU
  schedulerCron: "0 0 3 * * ?"

keystore:
  type: JKS
  filename: siva-keystore.jks
  password: siva-keystore-password