language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update && sudo apt-get install -y httpie
  - cp helper-scripts.conf.sample helper-scripts.conf
  - ./dev-setup.sh
  - ls -al
branches:
  only:
    - develop
install: true
script: ./mvnw clean package -Dmaven.test.skip.exec