language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - export TZ=Estonia/Tallinn
branches:
  only:
    - develop
install: true
script:
  - ./mvnw clean install
notifications:
  email:
    recipients:
      - mihkel.selgal@nortal.com
      - andres.voll@nortal.com
      - allan.juhanson@nortal.com
    on_success: never
    on_failure: always
