language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - export TZ=Estonia/Tallinn
branches:
  only:
    - develop
install: true
script:
  - ./mvnw clean install
notifications:
  emai