language: java
jdk:
  - openjdk7
  - oraclejdk7
before_install:
  - git submodule update --init --recursive
branches:
  only:
    - develop
install: true
script: ./mvnw clean package -Dmaven.test.skip.exec