language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - git submodule update --init --recursive
branches:
  only:
    - develop
install: true
script:
  - ./mvnw clean install
notifications:
  email: false