dist: xenial
language: java
sudo: false
cache: false
jdk:
- openjdk8
before_install:
- export TZ=Europe/Helsinki
branches:
  only:
  - develop
  - master
install: true
script: ./mvnw clean install -q -P\!dependency-check
after_success:
- "./mvnw jacoco:report coveralls:report -q -Dcoveralls.repo.token=$COVERALLS_REPO_TOKEN"
notifications:
  email:
    recipients:
    - andres.voll@nortal.com
    - aare.nurm@nortal.com
    - siim.suu@nortal.com
    - jorgen.heinsoo@nortal.com
    on_success: change
    on_failure: always
