site_name: SiVa - Validation Service Documentation
theme: material
repo_url: https://github.com/open-eid/SiVa
extra:
  font:
    code: 'Roboto Mono'
  palette:
    primary: 'Cyan'
    accent: 'Light Blue'
markdown_extensions:
  - codehilite
  - admonition
  - grid_tables
  - def_list
pages:
- Introduction: index.md
- Version info: siva/version_info.md
- Definitions: siva/definitions.md
- SiVa Service Overview: siva/overview.md
- Component diagram: siva/component_diagram.md
- Interfaces: siva/v2/interfaces.md
- Deployment: siva/v2/deployment.md
- Use cases: siva/use_cases.md
- Logging: siva/logging.md
- Quality Assurance Strategy: siva/qa_strategy.md
- Test Plan: siva/test_plan.md
- References: siva/references.md
- Appendixes:
      - Appendix 1 - Validation Policy: siva/appendix/validation_policy.md
      - Appendix 2 - Validation Constraint Configuration: siva/appendix/validation_constraints.md
      - Appendix 3 - Test Case Descriptions: siva/appendix/test_cases.md
      - Appendix 4 - WSDL of SOAP Interface : siva/appendix/wsdl.md
      - Appendix 5 - Known Issues : siva/appendix/known_issues.md
