site_name: SiVa - Validation Service Documentation
theme: material
repo_url: https://github.com/open-eid/SiVa
extra:
  font:
    code: 'Roboto Mono'
  palette:
    primary: 'Cyan'
    accent: 'Light Blue'
markdown_extensions:
  - codehilite
  - admonition
  - grid_tables
  - def_list
pages:
- VERSION HISTORY: siva/version_info.md
- INTRODUCTION: index.md
- 1. DEFINITIONS: siva/definitions.md
- 2. BACKGROUND: siva/overview.md
- 3. STRUCTURE & ACTIVITIES:
      - 3.1 Component model: siva/v2/structure_and_activities.md
      - 3.2 Use cases: siva/v2/use_cases.md
- 4. INTERFACES: siva/v2/interfaces.md
- 5. DEPLOYMENT:
      - 5.1 Deployment model: siva/v2/deployment.md
      - 5.2 System integrator's guide: siva/v2/systemintegrators_guide.md
- 6. QUALITY ASSURANCE: 
      - 6.1 QA Strategy: siva/qa_strategy.md
      - 6.2 Test Plan: siva/test_plan.md
- 7. REFERENCES: siva/references.md
- APPENDICES:
      - Appendix 1 - Validation Policy: siva/appendix/validation_policy.md
      - Appendix 2 - Test Case Descriptions: siva/appendix/test_cases.md
      - Appendix 3 - WSDL of SOAP Interface : siva/appendix/wsdl.md
      - Appendix 4 - Known Issues : siva/appendix/known_issues.md
