siva:
  pdf:
    signaturePolicy:
      policies:
        -
          name: POLv1
          description: asd
          url: bla
          constraintPath: pdf_constraint2.xml
        -
          name: POLv2
          description: asd
          url: bla
          constraintPath: pdf_constraint.xml
      defaultPolicy: POLv1
