server:
  port: 9000
  compression:
    enabled: true
spring:
  http:
    multipart:
      max-file-size: "10Mb"
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterAccess=20s
management:
  context-path: /monitoring
security:
  basic:
    path: /monitoring/**
wro4j:
  filterUrl: /owr
  managerFactory:
    preProcessors: removeSourceMaps, cssUrlRewriting, cssImport, cssMinJawr, semicolonAppender, jsMin
