server:
  port: 9000
siva:
  build:
    infoFile: "ci-build-info.yml"
  service:
    uploadDirectory: "upload-dir"
    serviceUrl: "http://localhost:8080/validate"
spring:
  http:
    multipart:
      max-file-size: "10Mb"